[[main]]
none = "none"

[[main]]
name = "Research"
pre = "lightbulb"
pageRef = "research"
identifier = "ICpkGNhalo"
weight = 9999

[[main]]
name = "Teaching"
pre = "heart"
pageRef = "teaching"
identifier = "NoG76jmGI3"
weight = 9999

[[main]]
name = "Resume"
pre = "graduation-cap"
pageRef = "resume"
identifier = "o90O7Jtj90"
weight = 9999

[[footer]]
none = "none"
