[[main]]
none = "none"

[[main]]
name = "Research"
pre = "lightbulb"
pageRef = "research"
identifier = "ICpkGNhalo"
weight = 3

[[main]]
name = "Teaching"
pre = "heart"
pageRef = "teaching"
identifier = "NoG76jmGI3"
weight = 4

[[main]]
name = "Resume"
pre = "graduation-cap"
pageRef = "resume"
identifier = "o90O7Jtj90"
weight = 5

[[main]]
name = "Human stuff"
pre = "ghost"
pageRef = "hobbies"
identifier = "rFohLlXlw6"
weight = 9999

[[footer]]
none = "none"
