colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableSearch = false
enableCodeCopy = true
highlightCurrentMenuArea = true
logo = "img/penguin.svg"
defaultBackgroundImage = "/img/background.svg"

[header]
layout = "basic"

[footer]
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "background"
showRecent = false
showRecentItems = 5
showMoreLink = false
showMoreLinkDest = "/posts"
cardView = false
cardViewScreenWidth = false
layoutBackgroundBlur = false

[article]
showDate = false
showDateUpdated = false
showAuthor = false
showHero = true
heroStyle = "background"
showBreadcrumbs = true
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = false
invertPagination = false
showReadingTime = false
showTableOfContents = true
showTaxonomies = false
showAuthorsBadges = false
showWordCount = false
showSummary = true
sharingLinks = []

[list]
showBreadcrumbs = false
showSummary = false
showTableOfContents = false
showCards = false
groupByYear = false
cardView = false
cardViewScreenWidth = false

[sitemap]
excludedKinds = []

[taxonomy]
showTermCount = false

[firebase]

[fathomAnalytics]

[verification]
